spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR}
      discovery:
        namespace: ${DISCOVERY_NAMESPACE}
      config:
        namespace: kk-game
        file-extension: yml
        group: DEFAULT_GROUP
        refresh-enabled: true
  config:
    import:
      - nacos:application.yml
      - nacos:redis.yml
      - nacos:gateway-server.yml